theme: jekyll-theme-minimal
# title: ğŸ‘ªğŸ²ğŸ‘¨â€ğŸ’» 
title: Dr. Christoph Stockhusen
description: [Email](mailto:mail@christophstockhusen.de) / [LinkedIn](https://www.linkedin.com/in/dr-christoph-stockhusen/)
logo: /assets/portrait.jpg
