plugins:
- jekyll-remote-theme
remote_theme: BDHU/minimalist
# remote_theme: pages-themes/minimal@v0.2.0
# title: ğŸ‘ªğŸ²ğŸ‘¨â€ğŸ’» 
title: Dr. Christoph Stockhusen
# description: 
logo: /assets/portrait.jpg
color-scheme: light
email: mail at [firstname][lastname] dot de

sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/christophstockhusen
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/dr-christoph-stockhusen/
  - name: XING
    icon: <i class="fa-brands fa-xing"></i>
    link: https://www.xing.com/profile/Christoph_Stockhusen
  - name: Google Scholar
    icon: <i class="fa-solid fa-graduation-cap"></i>
    link: https://scholar.google.com/citations?user=tZo-DMsAAAAJ
