plugins:
- jekyll-remote-theme
remote_theme: BDHU/minimalist
# remote_theme: pages-themes/minimal@v0.2.0
# theme: jekyll-theme-minimal
# title: ğŸ‘ªğŸ²ğŸ‘¨â€ğŸ’» 
title: Dr. Christoph Stockhusen
# description: 
logo: /assets/portrait.jpg
